// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhh0giMaoxyKVjz7U6_YH555doXWJLRFs',
    appId: '1:687014259299:web:ad80ce9080d01d3cdee656',
    messagingSenderId: '687014259299',
    projectId: 'nodemcu-592b5',
    authDomain: 'nodemcu-592b5.firebaseapp.com',
    databaseURL: 'https://nodemcu-592b5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nodemcu-592b5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwviWDptQOdYiVMCALTp-bTasztgdnjdU',
    appId: '1:687014259299:android:0f43dbfa78a11694dee656',
    messagingSenderId: '687014259299',
    projectId: 'nodemcu-592b5',
    databaseURL: 'https://nodemcu-592b5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nodemcu-592b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdTVmAPRoX5ri6cX54arKJQKYIfQprw5I',
    appId: '1:687014259299:ios:cb38bd1bc808a09ddee656',
    messagingSenderId: '687014259299',
    projectId: 'nodemcu-592b5',
    databaseURL: 'https://nodemcu-592b5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nodemcu-592b5.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdTVmAPRoX5ri6cX54arKJQKYIfQprw5I',
    appId: '1:687014259299:ios:cb38bd1bc808a09ddee656',
    messagingSenderId: '687014259299',
    projectId: 'nodemcu-592b5',
    databaseURL: 'https://nodemcu-592b5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nodemcu-592b5.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhh0giMaoxyKVjz7U6_YH555doXWJLRFs',
    appId: '1:687014259299:web:6eca65cf7a635d97dee656',
    messagingSenderId: '687014259299',
    projectId: 'nodemcu-592b5',
    authDomain: 'nodemcu-592b5.firebaseapp.com',
    databaseURL: 'https://nodemcu-592b5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nodemcu-592b5.firebasestorage.app',
  );
}
